apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
  labels:
    app: app2
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>app2</title></head>
    <body>
      <h1>Hello from app2</h1>
    </body>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  strategy: {}
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html
        configMap:
          name: app2-html
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app2
  name: app2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app2
  type: ClusterIP
status:
  loadBalancer: {}
