apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque #generic type 
data: 
  # base 64 encoded --> "echo -n <string> | base64""
  mongodb-user: bW9uZ29kYnVzZXI=
  mongodb-password: bW9uZ29kYnBhc3N3b3Jk