Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202510.26.0"
    config.vm.box_check_update = false

    config.vm.define "marloncoS" do |machine|
        machine.vm.hostname = "marloncoS"

        machine.vm.network "private_network",
        ip: "192.168.56.110"

        machine.vm.provision "shell",
        path: "scripts/provision_S.sh"

        machine.vm.provider "vmware_desktop" do |vmware|
            vmware.memory = 512
            vmware.cpus = 1
            vmware.vmx["displayName"] = "marloncoS"
        end
    end

end
