Vagrant.configure('2') do |config|

    config.vm.box = "bento/ubuntu-24.04"

    config.vm.provider "vmware_desktop" do |vmware|
        vmware.memory = 512
        vmware.cpus = 1
    end 
    

    config.vm.define "marloncoS" do |server|
    
        server.vm.hostname = "marloncoS"

        server.vm.network "private_network", 
         ip: '192.168.56.110'

        server.vm.provision "shell", 
         path: "provision_S.sh"
        
        # server.vm.provider "vmware_desktop" do |vmware|
        #     vmware.vmx["displayName"] = "marloncoS"
        # end

    end


    config.vm.define "marloncoSW" do |worker|

        worker.vm.hostname = "marloncoSW"
        
        worker.vm.network "private_network", 
         ip: '192.168.56.111'
        
        worker.vm.provision "shell", 
         path: "provision_SW.sh"
         
        # worker.vm.provider "vmware_desktop" do |vmware|
        #     vmware.vmx["displayName"] = "marloncoSW"
        # end

    end

end